# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Costctl < Formula
  desc "Multi-cloud cost and pricing CLI (Azure spot prices today)"
  homepage "https://github.com/jwmossmoz/costctl"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jwmossmoz/costctl/releases/download/v0.2.0/costctl_0.2.0_darwin_amd64.tar.gz"
      sha256 "cf94345dc8853fa28f36f08e4ac11b7196763260cebcaf7623310bb320ba654d"

      define_method(:install) do
        bin.install "costctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jwmossmoz/costctl/releases/download/v0.2.0/costctl_0.2.0_darwin_arm64.tar.gz"
      sha256 "275d23871ba1d1aaff7204f11b678cac5471c502e241fcd318c152eae2626594"

      define_method(:install) do
        bin.install "costctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jwmossmoz/costctl/releases/download/v0.2.0/costctl_0.2.0_linux_amd64.tar.gz"
      sha256 "cd1d8bf9a5770e4c0dea259bbe082f1c5182b88e7c7a0d1a713861d5bb7a0b0b"
      define_method(:install) do
        bin.install "costctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jwmossmoz/costctl/releases/download/v0.2.0/costctl_0.2.0_linux_arm64.tar.gz"
      sha256 "b9910b55ba0d721a5096e5ec28472e25c2c108ae71082224f9ae4687a66ca665"
      define_method(:install) do
        bin.install "costctl"
      end
    end
  end

  test do
    assert_match "costctl", shell_output("#{bin}/costctl --version")
  end
end
