# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Costctl < Formula
  desc "Multi-cloud cost and pricing CLI (Azure spot prices today)"
  homepage "https://github.com/jwmossmoz/costctl"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jwmossmoz/costctl/releases/download/v0.3.1/costctl_0.3.1_darwin_amd64.tar.gz"
      sha256 "88b0bd06ae6b2e07b9b4519e48f1d791c392363fa7e5495d6aa84c763b811fab"

      define_method(:install) do
        bin.install "costctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jwmossmoz/costctl/releases/download/v0.3.1/costctl_0.3.1_darwin_arm64.tar.gz"
      sha256 "8b9d483be603eca531dc5be383d9f13e48d1ad9cf8757a8982b0708619e95981"

      define_method(:install) do
        bin.install "costctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jwmossmoz/costctl/releases/download/v0.3.1/costctl_0.3.1_linux_amd64.tar.gz"
      sha256 "2bd7538384be865c068daac522b118d603e5dbe41c515d1ef2c787bdf3915c46"
      define_method(:install) do
        bin.install "costctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jwmossmoz/costctl/releases/download/v0.3.1/costctl_0.3.1_linux_arm64.tar.gz"
      sha256 "55ccd552b1a93bceb5bc16ab40e80f180e4d15aeb854af469f579d7efed5d4d7"
      define_method(:install) do
        bin.install "costctl"
      end
    end
  end

  test do
    assert_match "costctl", shell_output("#{bin}/costctl --version")
  end
end
