# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trybox < Formula
  desc "Fresh VM. Dirty checkout. Exact command."
  homepage "https://github.com/jwmossmoz/trybox"
  version "0.1.1"
  license "MIT"

  depends_on "cirruslabs/cli/tart"
  depends_on "hashicorp/tap/packer"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/jwmossmoz/trybox/releases/download/v0.1.1/trybox_0.1.1_darwin_arm64.tar.gz"
    sha256 "68192d7642c95e943a3e33bf50b528d60b8764310850de2942962dd6c0888c6c"

    define_method(:install) do
      if build.head?
        ldflags = "-s -w -X github.com/jwmossmoz/trybox/internal/cli.Version=#{version}"
        system "go", "build", *std_go_args(output: bin/"trybox", ldflags: ldflags), "./cmd/trybox"
      else
        bin.install "trybox"
      end
    end
  end

  head do
    url "https://github.com/jwmossmoz/trybox.git", branch: "main"
    depends_on "go" => :build
  end
  depends_on arch: :arm64

  test do
    assert_match version.to_s, shell_output("#{bin}/trybox version")
  end
end
