# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trybox < Formula
  desc "Fresh VM. Dirty checkout. Exact command."
  homepage "https://github.com/jwmossmoz/trybox"
  version "0.1.0"
  license "MIT"

  depends_on "cirruslabs/cli/tart"
  depends_on "hashicorp/tap/packer"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/jwmossmoz/trybox/releases/download/v0.1.0/trybox_0.1.0_darwin_arm64.tar.gz"
    sha256 "9ef8d623f549bcc361bd4705e681c918f3c689bca19156600c9afd1db0f47759"

    define_method(:install) do
      bin.install "trybox"
    end
  end

  depends_on arch: :arm64

  test do
    assert_match version.to_s, shell_output("#{bin}/trybox version")
  end
end
